name: Cubed

on:
  push:
  pull_request:
  # manual trigger
  workflow_dispatch:

jobs:
  build:
    # This workflow only runs on the origin org
    # if: github.repository_owner == 'sgkit-dev'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v7
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v7
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up uv
      uses: astral-sh/setup-uv@v10.0.1
      with:
        version: "0.12.10"
        python-version: ${{ matrix.python-version }}
        enable-cache: true

    - name: Install deps and sgkit
      run: |
        uv sync --locked --all-extras --python "${{ matrix.python-version }}"
        uv pip install --python .venv/bin/python --upgrade git+https://github.com/cubed-dev/cubed.git git+https://github.com/cubed-dev/cubed-xarray.git git+https://github.com/pydata/xarray.git

    - name: Test with pytest
      run: |
        uv run --no-sync pytest -v sgkit/tests/test_{aggregation,association,hwe,pca,window}.py \
          -k "test_count_call_alleles or \
              test_gwas_linear_regression or \
              test_hwep or \
              test_sample_stats or \
              (test_count_variant_alleles and not test_count_variant_alleles__chunked[call_genotype]) or \
              (test_variant_stats and not test_variant_stats__chunks[chunks2-False]) or \
              (test_pca__array_backend and tsqr) or \
              (test_window and not 12-5-4-4)" \
          --use-cubed
